/**
 * Existing published trips matched from the visited-places Excel import.
 *
 * Generated by scripts/import-visited-places.py.
 */

export const visitedByMilanaMatchedSlugs = [
  "nitzanim-lake",
  "nchl-dn",
  "brykt-rm-msdh",
  "chrmvn",
  "gmvn-hchvlh",
  "nahal-hashofet",
  "myyn-hsvsym",
  "shmvrt-tb-bnys",
  "mpl-tnvr-gbvl-lbnvn",
  "nchl-nkrvt-yknm",
  "rvb-rvy",
  "nchl-hkybvtzym",
  "nchl-hsy",
  "chvrsht-gdvnh",
  "shmvrt-tb-gml",
  "myyn-chrvd",
  "gny-chvgh",
  "rsh-hnkrh",
  "yn-chrdlyt",
  "hchvf-shl-mvsh-kzyb",
  "bt-shlmh",
  "ein-moda",
  "ein-bokek",
  "sataf",
] as const;

export type VisitedByMilanaMatchedSlug =
  (typeof visitedByMilanaMatchedSlugs)[number];
