/**
 * Existing published trips matched from the visited-places Excel import.
 *
 * Generated by scripts/import-visited-places.py.
 */

export const visitedByMilanaMatchedSlugs = [
  "nitzanim-lake",
  "nchl-dn",
  "ein-moda",
  "ein-bokek",
  "sataf",
] as const;

export type VisitedByMilanaMatchedSlug =
  (typeof visitedByMilanaMatchedSlugs)[number];
